name: Sync Upstream

on:
  schedule:
    - cron:  '0 * * * *'
    # Runs once an hour

  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with starter code

    steps:
      - name: "Checkout main"
        uses: actions/checkout@v2
        
      - name: Pull (Fast-Forward) upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
        with:
          upstream_repository: ApolloPavilion/original
          upstream_branch: main
          target_branch: main
          git_pull_args: --ff-only                    # optional arg use, defaults to simple 'pull'
          github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication

      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits
        run: echo "There were new commits."
